### PR TITLE
fix postalcode hierarchies by running pip

### LINKED ISSUE #2177: Postalcode in Switzerland with bad hierarchy
Hello everyone, I was investigating some strange results from Pelias for Switzerland. It appears that the postalcode dataset has been updated a rather long time ago ~2017

Since then, the admin database has been greatly improved in 2019.

As a result many postalcodes have a wrong locality/localadmin attached to their hierarchy. For instance 1815 (Clarens/Montreux) has "Lac Léman" as a direct parent, or 1020 Renens has Lausanne as direct parent.

From what I understood navigating the various repository and past issues, it seems that the hierarchy of the postalcodes should be updated (by running pip using the updated admin dataset?). Is there some documentation on how to do that and propose an update? Or would someone have an existing setup that would make this action relatively easy?

Please let me know what would be the best way forward to improve this point 🙂

### PR DESCRIPTION
**Pull request by slvlirnoff**
Should fix https://github.com/whosonfirst-data/whosonfirst-data/issues/2177

I've setup pelias/spatial locally and after various small changes to the python scripts I've managed to update the hierarchy.

Could you help me with checking the results and changes @stepps00 ?

Also is there a trick to create a pull requests in github? It almost killed my browser going through the create pull request tab :-)

### CODE REVIEW

**Comment by stepps00** [comment]
@slvlirnoff at first glance, this looks great! Before merging, I'd like to pull the changes down locally to review the updated hierarchies. If everything looks good, we should be able to merge.

As for a trick to view PRs in Github.. unfortunately, Github recently made changes that cause large diffs to load quite slow (or not load at all) on the /files page, so no real work around other than pulling the changes down locally for review.

cc @nvkelso

**Comment by nvkelso** [comment]
Nice! I eyeballed a couple and the only thing I noticed is the `mz:is_current` is being set to `-1` (unknown) via Exportify tools, but since we know these are all current we could in the PR set those to `1` (current) instead as a "nice to have" (not a blocker, just better practice).

**Comment by slvlirnoff** [comment]
I'm considering updating the dataset with the latest swisstopo export since it's a bit old now. It would be a good time to update is_current then I would think. A few records seems to have boggus coordinates and I'd maybe not want to set them to is_current=1 now.

**Comment by nvkelso** [comment]
Sounds good to me to split the work in two: merge this PR now and following later with the Swisstopo data update and `mz:is_current`.

@stepps00 can you look at this PR this week so we can get it merged? Thanks :)

**Comment by stepps00** [comment]
I pulled these changes down and reviewed them locally, all of the changes look as expected. In some cases, a postalcode record is receiving a changed locality and/or county id in their hierarchy but in most cases it looks like a new locality id is being added to the existing hierarchy.

I'll merge this PR now so we can track follow up swisstopo updates separately. Thank you @slvlirnoff!

**Review by stepps00 — COMMENTED** [review]
LGTM, merged

**Pull request merged**
